### ISSUE TITLE
Using bot with Telegram Desktop

### ISSUE THREAD

**Issue by sovesti** [Dannypa/WeatherBot#1]
Currently bot can't be used anywhere else except mobile version of Telegram because it requires location sharing. Maybe you can add an option of passing your location to bot by text? For example, by coordinates or by the name of town.

![image](https://user-images.githubusercontent.com/54536929/176835667-b235714e-cd37-42ec-9552-c2e029d8ef27.png)

**Comment by Dannypa** [comment]
This actually is possible; you can pass location by text instead of pressing the "share location" button.
![image](https://user-images.githubusercontent.com/57408003/176847021-6c16bd28-ff2d-448e-b947-f70bd4f88820.png)
